import { FormEvent, useEffect, useState } from "react";
import { Bell, Check, Crown, LogOut, Monitor, Pencil, Plus, ShieldCheck, Trash2, UserCircle, X } from "lucide-react";
import type { AppNotification, Plan, Profile, User } from "../../../../packages/shared-types/src/index";
import { api } from "../services/api";
import { confirmDialog, promptDialog } from "./AppDialog";

type Session={id:string;userAgent:string;ipAddress:string;lastSeenAt:string;createdAt:string;expiresAt:string;current:boolean};
type Tab="account"|"profiles"|"security"|"devices"|"notifications"|"plans";
type Props={user:User;activeProfileId:string|null;onClose:()=>void;onUserChange:(user:User)=>void;onProfileSwitch:(id:string)=>Promise<void>;onLogout:()=>void};

export function AccountCenter({user,activeProfileId,onClose,onUserChange,onProfileSwitch,onLogout}:Props){
 const[tab,setTab]=useState<Tab>("account"),[notifications,setNotifications]=useState<AppNotification[]>([]),[plans,setPlans]=useState<Plan[]>([]),[currentPlan,setCurrentPlan]=useState<string>(user.subscriptionTier),[sessions,setSessions]=useState<Session[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[displayName,setDisplayName]=useState(user.displayName),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[newProfileName,setNewProfileName]=useState(""),[newProfileKids,setNewProfileKids]=useState(false);
 useEffect(()=>{api.notifications().then(x=>setNotifications(x.items)).catch(()=>{});api.plans().then(setPlans).catch(()=>{});api.subscription().then(x=>x&&setCurrentPlan(x.plan)).catch(()=>{});api.sessions().then(setSessions).catch(()=>{})},[]);
 const run=async(key:string,action:()=>Promise<void>)=>{setBusy(key);setError("");setMessage("");try{await action()}catch(e){setError(e instanceof Error?e.message:"Thao tác thất bại")}finally{setBusy("")}};
 async function read(item:AppNotification){if(!item.readAt){await api.readNotification(item.id);setNotifications(list=>list.map(x=>x.id===item.id?{...x,readAt:new Date().toISOString()}:x))}}
 const saveAccount=(e:FormEvent)=>{e.preventDefault();void run("account",async()=>{const next=await api.updateMe(displayName.trim());onUserChange(next);setMessage("Đã cập nhật thông tin tài khoản.")})};
 const changePassword=(e:FormEvent)=>{e.preventDefault();if(newPassword!==confirmPassword){setError("Mật khẩu xác nhận không khớp");return}void run("password",async()=>{await api.changePassword(currentPassword,newPassword);setCurrentPassword("");setNewPassword("");setConfirmPassword("");setMessage("Đã đổi mật khẩu và đăng xuất các thiết bị khác.");setSessions(await api.sessions())})};
 const createProfile=(e:FormEvent)=>{e.preventDefault();void run("profile-new",async()=>{await api.createProfile({name:newProfileName.trim(),isKids:newProfileKids});onUserChange(await api.me());setNewProfileName("");setNewProfileKids(false);setMessage("Đã tạo hồ sơ mới.")})};
 const editProfile=async(profile:Profile)=>{const name=await promptDialog({title:"Đổi tên hồ sơ",message:`Cập nhật tên hiển thị cho hồ sơ “${profile.name}”.`,defaultValue:profile.name,confirmLabel:"Lưu tên"});if(name===null||!name.trim())return;void run(profile.id,async()=>{await api.updateProfile(profile.id,{name:name.trim()});onUserChange(await api.me());setMessage("Đã cập nhật hồ sơ.")})};
 const removeProfile=async(profile:Profile)=>{if(!await confirmDialog({title:"Xóa hồ sơ?",message:`Hồ sơ “${profile.name}” và lịch sử xem riêng có thể không khôi phục được.`,confirmLabel:"Xóa hồ sơ",tone:"danger"}))return;void run(profile.id,async()=>{await api.deleteProfile(profile.id);onUserChange(await api.me());setMessage("Đã xóa hồ sơ.")})};
 const subscribe=(plan:Plan)=>void run(plan.id,async()=>{await api.subscribe(plan.id);setCurrentPlan(plan.name);setMessage("Đã cập nhật gói dịch vụ.")});
 const revoke=(session:Session)=>void run(session.id,async()=>{await api.revokeSession(session.id);setSessions(await api.sessions());setMessage("Đã đăng xuất thiết bị.")});
 const logout=async()=>{if(!await confirmDialog({title:"Đăng xuất khỏi NexaPlay?",message:"Bạn sẽ cần đăng nhập lại để tiếp tục xem danh sách và nội dung cá nhân.",confirmLabel:"Đăng xuất",cancelLabel:"Ở lại",tone:"danger"}))return;onClose();onLogout()};
 return <div className="modal-shell" role="dialog" aria-modal="true"><section className="account-center account-service-center"><header><div><span className="eyebrow">Trung tâm tài khoản</span><h2>Xin chào, {user.displayName}</h2><small>{user.email}</small></div><button className="icon-button" onClick={onClose}><X/></button></header>
 <div className="account-service-layout"><nav className="account-tabs account-tabs--vertical"><button className={tab==="account"?"active":""} onClick={()=>setTab("account")}><UserCircle/>Tài khoản</button><button className={tab==="profiles"?"active":""} onClick={()=>setTab("profiles")}><Pencil/>Hồ sơ xem</button><button className={tab==="security"?"active":""} onClick={()=>setTab("security")}><ShieldCheck/>Mật khẩu</button><button className={tab==="devices"?"active":""} onClick={()=>setTab("devices")}><Monitor/>Thiết bị</button><button className={tab==="notifications"?"active":""} onClick={()=>setTab("notifications")}><Bell/>Thông báo</button><button className={tab==="plans"?"active":""} onClick={()=>setTab("plans")}><Crown/>Gói dịch vụ</button><button className="account-logout" onClick={logout}><LogOut/>Đăng xuất tài khoản</button></nav>
 <main className="account-service-content">{error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}
 {tab==="account"&&<form className="account-form" onSubmit={saveAccount}><h3>Thông tin cá nhân</h3><label>Email<input value={user.email} disabled/><small>Email đăng nhập không thể tự thay đổi.</small></label><label>Tên hiển thị<input value={displayName} onChange={e=>setDisplayName(e.target.value)} required minLength={2} maxLength={80}/></label><label>Vai trò<input value={user.role} disabled/></label><button className="primary-button" disabled={busy==="account"||displayName.trim()===user.displayName}>Lưu thay đổi</button></form>}
 {tab==="profiles"&&<><div className="account-section-heading"><div><h3>Hồ sơ xem phim</h3><p>Mỗi hồ sơ có danh sách và trải nghiệm xem riêng.</p></div></div><div className="profile-manager">{user.profiles.map(profile=><article className={profile.id===activeProfileId?"active":""} key={profile.id}><img src={profile.avatarUrl}/><span><strong>{profile.name}</strong><small>{profile.isKids?"Hồ sơ trẻ em":"Hồ sơ tiêu chuẩn"}{profile.id===activeProfileId?" · Đang dùng":""}</small></span><div>{profile.id!==activeProfileId&&<button onClick={()=>void onProfileSwitch(profile.id)}>Chọn</button>}<button disabled={busy===profile.id} onClick={()=>editProfile(profile)}><Pencil/></button><button disabled={busy===profile.id} onClick={()=>removeProfile(profile)}><Trash2/></button></div></article>)}</div><form className="profile-create" onSubmit={createProfile}><h4><Plus/>Thêm hồ sơ</h4><input value={newProfileName} onChange={e=>setNewProfileName(e.target.value)} placeholder="Tên hồ sơ" required maxLength={40}/><label><input type="checkbox" checked={newProfileKids} onChange={e=>setNewProfileKids(e.target.checked)}/> Hồ sơ trẻ em</label><button className="secondary-button" disabled={busy==="profile-new"}>Tạo hồ sơ</button></form></>}
 {tab==="security"&&<form className="account-form" onSubmit={changePassword}><h3>Đổi mật khẩu</h3><p>Mật khẩu mới phải có ít nhất 10 ký tự. Các thiết bị khác sẽ bị đăng xuất.</p><label>Mật khẩu hiện tại<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required autoComplete="current-password"/></label><label>Mật khẩu mới<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required minLength={10} autoComplete="new-password"/></label><label>Xác nhận mật khẩu<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required minLength={10}/></label><button className="primary-button" disabled={busy==="password"}>Đổi mật khẩu</button></form>}
 {tab==="devices"&&<><div className="account-section-heading"><div><h3>Thiết bị đăng nhập</h3><p>Kiểm tra và đăng xuất các phiên bạn không nhận ra.</p></div><button className="secondary-button" onClick={()=>void run("all-sessions",async()=>{await api.revokeOtherSessions();setSessions(await api.sessions());setMessage("Đã đăng xuất tất cả thiết bị khác.")})}>Đăng xuất thiết bị khác</button></div><div className="session-list">{sessions.map(session=><article key={session.id}><Monitor/><span><strong>{session.userAgent||"Thiết bị không xác định"}</strong><small>{session.ipAddress||"Không rõ IP"} · Hoạt động {new Date(session.lastSeenAt).toLocaleString("vi-VN")}</small></span>{session.current?<i>Thiết bị này</i>:<button disabled={busy===session.id} onClick={()=>revoke(session)}>Đăng xuất</button>}</article>)}</div></>}
 {tab==="notifications"&&<div className="notification-list">{notifications.length?notifications.map(item=><button key={item.id} className={`notification-item ${item.readAt?"":"unread"}`} onClick={()=>read(item)}><span className="notification-dot"/><div><strong>{item.title}</strong><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString("vi-VN")}</small></div></button>):<p className="empty-state">Bạn chưa có thông báo mới.</p>}</div>}
 {tab==="plans"&&<div className="plan-grid">{plans.map(plan=><article className={`plan-card ${currentPlan===plan.name?"current":""}`} key={plan.id}><div><span className="eyebrow">{plan.maxQuality}</span><h3>{plan.name}</h3><strong className="plan-price">{plan.price?`${plan.price.toLocaleString("vi-VN")}đ`:"Miễn phí"}<small>/tháng</small></strong></div><ul>{plan.features.map(feature=><li key={feature}><Check/>{feature}</li>)}</ul><button className={currentPlan===plan.name?"secondary-button":"primary-button"} disabled={currentPlan===plan.name||!!busy} onClick={()=>subscribe(plan)}>{currentPlan===plan.name?"Gói hiện tại":busy===plan.id?"Đang xử lý...":"Chọn gói"}</button></article>)}</div>}
 </main></div></section></div>
}
