import "dotenv/config";
import express from "express";
import { nanoid } from "nanoid";
import { z } from "zod";
import { asyncHandler,createPool,errorMiddleware,fail,health,identity,ok,requireIdentity } from "@movie-platform/service-kit";
const app=express(),pool=createPool("engagement_db");app.use(express.json());app.get("/health",health("engagement-service",pool));app.use("/v1",requireIdentity);

app.get("/v1/users/me/watchlist",asyncHandler(async(req,res)=>{const rows=await pool.query("SELECT content_id,added_at FROM watchlist_items WHERE profile_id=$1 ORDER BY added_at DESC",[identity(req)!.profileId]);ok(res,rows.rows.map(r=>({contentId:r.content_id,addedAt:r.added_at})))}));
app.post("/v1/users/me/watchlist",asyncHandler(async(req,res)=>{const parsed=z.object({movieId:z.string()}).safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","movieId is required");await pool.query("INSERT INTO watchlist_items(id,profile_id,content_id) VALUES($1,$2,$3) ON CONFLICT(profile_id,content_id) DO NOTHING",[`wat_${nanoid(16)}`,identity(req)!.profileId,parsed.data.movieId]);ok(res,{added:parsed.data.movieId})}));
app.delete("/v1/users/me/watchlist/:movieId",asyncHandler(async(req,res)=>{await pool.query("DELETE FROM watchlist_items WHERE profile_id=$1 AND content_id=$2",[identity(req)!.profileId,req.params.movieId]);ok(res,{removed:req.params.movieId})}));
app.post("/v1/users/me/progress",asyncHandler(async(req,res)=>{const parsed=z.object({movieId:z.string().min(1).max(160),progress:z.number().min(0).max(100),positionSeconds:z.number().int().nonnegative().optional(),durationSeconds:z.number().int().positive().optional(),episodeSlug:z.string().max(120).optional(),episodeName:z.string().max(120).optional(),serverName:z.string().max(120).optional()}).safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","Invalid playback progress",parsed.error.flatten());const v=parsed.data,completed=v.progress>=90;await pool.query(`INSERT INTO watch_progress(id,profile_id,content_id,episode_slug,episode_name,server_name,progress,position_seconds,duration_seconds,is_completed,last_watched_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,NOW()) ON CONFLICT(profile_id,content_id) DO UPDATE SET episode_slug=EXCLUDED.episode_slug,episode_name=EXCLUDED.episode_name,server_name=EXCLUDED.server_name,progress=EXCLUDED.progress,position_seconds=EXCLUDED.position_seconds,duration_seconds=EXCLUDED.duration_seconds,is_completed=EXCLUDED.is_completed,last_watched_at=NOW()`,[`prg_${nanoid(16)}`,identity(req)!.profileId,v.movieId,v.episodeSlug??null,v.episodeName??null,v.serverName??null,v.progress,v.positionSeconds??0,v.durationSeconds??1,completed]);await pool.query("INSERT INTO watch_events(profile_id,content_id,event_type,episode_slug,progress,position_seconds,occurred_at) VALUES($1,$2,$3,$4,$5,$6,NOW())",[identity(req)!.profileId,v.movieId,completed?"complete":v.progress<=1?"play":"progress",v.episodeSlug??null,v.progress,v.positionSeconds??0]);ok(res,{movieId:v.movieId,progress:v.progress,completed,episodeSlug:v.episodeSlug})}));
const progressFields="content_id,episode_slug,episode_name,server_name,progress,position_seconds,duration_seconds,is_completed,last_watched_at";
const progressDto=(r:any)=>({contentId:r.content_id,episodeSlug:r.episode_slug,episodeName:r.episode_name,serverName:r.server_name,progress:r.progress,positionSeconds:r.position_seconds,durationSeconds:r.duration_seconds,completed:r.is_completed,lastWatchedAt:r.last_watched_at});
app.get("/v1/engagement/progress",asyncHandler(async(req,res)=>{const rows=await pool.query(`SELECT ${progressFields} FROM watch_progress WHERE profile_id=$1`,[identity(req)!.profileId]);ok(res,rows.rows.map(progressDto))}));
app.get("/v1/engagement/continue-watching",asyncHandler(async(req,res)=>{const rows=await pool.query(`SELECT ${progressFields} FROM watch_progress WHERE profile_id=$1 AND is_completed=FALSE AND progress>0 ORDER BY last_watched_at DESC LIMIT 20`,[identity(req)!.profileId]);ok(res,rows.rows.map(progressDto))}));
app.get("/v1/engagement/history",asyncHandler(async(req,res)=>{const rows=await pool.query(`SELECT ${progressFields} FROM watch_progress WHERE profile_id=$1 ORDER BY last_watched_at DESC LIMIT 100`,[identity(req)!.profileId]);ok(res,rows.rows.map(progressDto))}));
app.get("/v1/engagement/watched-episodes/:contentId",asyncHandler(async(req,res)=>{const rows=await pool.query("SELECT episode_slug,MAX(occurred_at) last_watched_at FROM watch_events WHERE profile_id=$1 AND content_id=$2 AND episode_slug IS NOT NULL GROUP BY episode_slug ORDER BY last_watched_at DESC",[identity(req)!.profileId,req.params.contentId]);ok(res,rows.rows.map(row=>({episodeSlug:row.episode_slug,lastWatchedAt:row.last_watched_at})))}));
app.delete("/v1/engagement/history/:contentId",asyncHandler(async(req,res)=>{await pool.query("DELETE FROM watch_progress WHERE profile_id=$1 AND content_id=$2",[identity(req)!.profileId,req.params.contentId]);ok(res,{removed:req.params.contentId})}));
app.use(errorMiddleware);async function start(){try{await pool.query("ALTER TABLE watchlist_items ALTER COLUMN content_id TYPE varchar(160)");await pool.query("ALTER TABLE watch_progress ALTER COLUMN content_id TYPE varchar(160),ADD COLUMN IF NOT EXISTS episode_slug varchar(120),ADD COLUMN IF NOT EXISTS episode_name varchar(120),ADD COLUMN IF NOT EXISTS server_name varchar(120)");await pool.query("ALTER TABLE watch_events ALTER COLUMN content_id TYPE varchar(160),ADD COLUMN IF NOT EXISTS episode_slug varchar(120)")}catch(error){console.error("engagement migration skipped",error)}app.listen(Number(process.env.PORT??4103),()=>console.log("engagement-service listening"))}void start();
