import "dotenv/config";
import express from "express";
import { nanoid } from "nanoid";
import { z } from "zod";
import { asyncHandler, createPool, errorMiddleware, fail, health, ok, requireAdmin } from "@movie-platform/service-kit";
import { adminContentRouter } from "./admin-content.routes.js";
import { adminGenresRouter } from "./admin-genres.routes.js";

const app=express(), pool=createPool("catalog_db");
app.use(express.json({limit:"2mb"})); app.get("/health",health("catalog-service",pool));
const OPHIM_BASE=(process.env.OPHIM_API_URL??"https://ophim1.com/v1/api").replace(/\/$/,"");
const OPHIM_CDN="https://img.ophim.live/uploads/movies";
const genreSeed=[['hanh-dong','Hành Động'],['tinh-cam','Tình Cảm'],['hai-huoc','Hài Hước'],['co-trang','Cổ Trang'],['tam-ly','Tâm Lý'],['hinh-su','Hình Sự'],['chien-tranh','Chiến Tranh'],['the-thao','Thể Thao'],['vo-thuat','Võ Thuật'],['vien-tuong','Viễn Tưởng'],['phieu-luu','Phiêu Lưu'],['khoa-hoc','Khoa Học'],['kinh-di','Kinh Dị'],['am-nhac','Âm Nhạc'],['than-thoai','Thần Thoại'],['tai-lieu','Tài Liệu'],['gia-dinh','Gia Đình'],['chinh-kich','Chính Kịch'],['bi-an','Bí Ẩn']];
function imageUrl(value:string|undefined,cdn=OPHIM_CDN){if(!value)return "";if(/^https?:\/\//.test(value))return value;return `${cdn}/${value.replace(/^\/uploads\/movies\//,'')}`}
function minutes(value:any){const match=String(value??'').match(/\d+/);return match?Number(match[0]):0}
function mapOphim(item:any,cdn=OPHIM_CDN,detail=false){const rating=Number(item.tmdb?.vote_average||item.imdb?.vote_average||0);return {id:item.slug,title:item.name??'',originalTitle:item.origin_name??'',description:String(item.content??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()||'Thông tin nội dung đang được cập nhật.',year:Number(item.year)||0,durationMinutes:minutes(item.time),ageRating:item.quality??'HD',rating:Math.round(rating*10)/10,matchScore:Math.min(99,Math.max(70,Math.round(75+rating*2))),type:item.type==='single'?'movie':'series',director:(item.director??[]).filter((x:string)=>x&&x!=='Đang cập nhật').join(', ')||'Đang cập nhật',posterUrl:imageUrl(item.thumb_url,cdn),backdropUrl:imageUrl(item.poster_url||item.thumb_url,cdn),trailerUrl:item.trailer_url??'',genres:(item.category??[]).map((x:any)=>x.name),genreSlugs:(item.category??[]).map((x:any)=>x.slug),cast:item.actor??[],isTrending:true,isFeatured:false,slug:item.slug,quality:item.quality,language:item.lang,episodeCurrent:item.episode_current,country:(item.country??[]).map((x:any)=>x.name),episodes:detail?(item.episodes??[]).map((server:any)=>({name:server.server_name,episodes:(server.server_data??[]).map((episode:any)=>({name:episode.name,slug:episode.slug,filename:episode.filename,embedUrl:episode.link_embed,m3u8Url:episode.link_m3u8}))})):undefined}}
const memoryCache=new Map<string,{payload:any,expires:number}>();
async function fetchOphim(path:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${OPHIM_BASE}${path}`,{signal:controller.signal,headers:{accept:'application/json','user-agent':'MoviePlatform/1.0'}});if(!response.ok)throw new Error(`OPhim ${response.status}`);return await response.json()}finally{clearTimeout(timer)}}
async function cachedOphim(path:string,ttlSeconds=300){const key=`ophim:${path}`,now=Date.now(),memory=memoryCache.get(key);if(memory&&memory.expires>now)return {payload:memory.payload,cache:'memory'};try{const row=(await pool.query('SELECT payload,expires_at FROM external_api_cache WHERE cache_key=$1',[key])).rows[0];if(row&&new Date(row.expires_at).getTime()>now){memoryCache.set(key,{payload:row.payload,expires:new Date(row.expires_at).getTime()});return {payload:row.payload,cache:'database'}}}catch{}try{const payload=await fetchOphim(path),expires=now+ttlSeconds*1000;memoryCache.set(key,{payload,expires});pool.query(`INSERT INTO external_api_cache(cache_key,payload,fetched_at,expires_at) VALUES($1,$2,NOW(),$3) ON CONFLICT(cache_key) DO UPDATE SET payload=EXCLUDED.payload,fetched_at=NOW(),expires_at=EXCLUDED.expires_at`,[key,payload,new Date(expires)]).catch(()=>{});return {payload,cache:'miss'}}catch(error){if(memory)return {payload:memory.payload,cache:'stale-memory'};try{const stale=(await pool.query('SELECT payload FROM external_api_cache WHERE cache_key=$1',[key])).rows[0];if(stale)return {payload:stale.payload,cache:'stale-database'}}catch{}throw error}}
app.get('/v1/ophim/home',asyncHandler(async(_req,res)=>{const {payload,cache}=await cachedOphim('/home',180);const cdn=payload.data?.APP_DOMAIN_CDN_IMAGE?`${payload.data.APP_DOMAIN_CDN_IMAGE}/uploads/movies`:OPHIM_CDN;const incoming=(payload.data?.items??[]).map((x:any)=>mapOphim(x,cdn));if(incoming[0])incoming[0].isFeatured=true;await syncOphim(incoming);ok(res,await overlayOphim(incoming),{source:'catalog',upstream:'ophim',cache})}));
app.get('/v1/ophim/hot',asyncHandler(async(_req,res)=>{const {payload,cache}=await cachedOphim('/danh-sach/phim-moi-cap-nhat?page=1&year=2026&sort_field=view&sort_type=desc',600);const cdn=payload.data?.APP_DOMAIN_CDN_IMAGE?`${payload.data.APP_DOMAIN_CDN_IMAGE}/uploads/movies`:OPHIM_CDN;const incoming=(payload.data?.items??[]).filter((item:any)=>Number(item.year)===2026).map((item:any)=>mapOphim(item,cdn));await syncOphim(incoming);const movies=(await overlayOphim(incoming)).map((item:any,index:number)=>({...item,hotRank:index+1}));ok(res,movies,{source:'catalog',upstream:'ophim',ranking:'view',year:2026,cache,refreshedAt:new Date().toISOString()})}));
app.get('/v1/ophim/movies',asyncHandler(async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),genre=String(req.query.genre??''),country=String(req.query.country??''),type=String(req.query.type??'');let path='/danh-sach/phim-moi-cap-nhat';if(genre)path=`/the-loai/${encodeURIComponent(genre)}`;else if(country)path=`/quoc-gia/${encodeURIComponent(country)}`;else if(type)path=`/danh-sach/${encodeURIComponent(type)}`;const {payload,cache}=await cachedOphim(`${path}?page=${page}`,300);const cdn=payload.data?.APP_DOMAIN_CDN_IMAGE?`${payload.data.APP_DOMAIN_CDN_IMAGE}/uploads/movies`:OPHIM_CDN;const incoming=(payload.data?.items??[]).map((x:any)=>mapOphim(x,cdn));await syncOphim(incoming);ok(res,await overlayOphim(incoming),{...(payload.data?.params?.pagination??{page}),source:'catalog',upstream:'ophim',cache})}));
app.get('/v1/ophim/movies/:slug',asyncHandler(async(req,res)=>{const {payload,cache}=await cachedOphim(`/phim/${encodeURIComponent(req.params.slug)}`,120);if(!payload.data?.item)return fail(res,404,'MOVIE_NOT_FOUND','Không tìm thấy phim');const incoming=mapOphim(payload.data.item,payload.data.APP_DOMAIN_CDN_IMAGE?`${payload.data.APP_DOMAIN_CDN_IMAGE}/uploads/movies`:OPHIM_CDN,true);await syncOphim([incoming]);const [movie]=await overlayOphim([incoming]);if(!movie)return fail(res,404,'MOVIE_NOT_FOUND','Phim đã bị ẩn khỏi catalog');ok(res,movie,{source:'catalog',upstream:'ophim',cache})}));
app.get('/v1/ophim/search',asyncHandler(async(req,res)=>{const keyword=String(req.query.q??'').trim();if(!keyword)return ok(res,[]);const {payload,cache}=await cachedOphim(`/tim-kiem?keyword=${encodeURIComponent(keyword)}&page=${Math.max(1,Number(req.query.page)||1)}`,120);const cdn=payload.data?.APP_DOMAIN_CDN_IMAGE?`${payload.data.APP_DOMAIN_CDN_IMAGE}/uploads/movies`:OPHIM_CDN;const incoming=(payload.data?.items??[]).map((x:any)=>mapOphim(x,cdn));await syncOphim(incoming);ok(res,await overlayOphim(incoming),{...(payload.data?.params?.pagination??{}),source:'catalog',upstream:'ophim',cache})}));
app.get('/v1/ophim/genres',asyncHandler(async(_req,res)=>ok(res,(await pool.query("SELECT id,name,slug FROM genres WHERE active=TRUE ORDER BY position,name")).rows)));
const mapMovie=(r:any)=>({id:r.id,title:r.title,originalTitle:r.original_title,description:r.description,year:r.release_year,durationMinutes:r.duration_minutes,ageRating:r.age_rating,rating:Number(r.rating),matchScore:r.match_score,type:r.content_type,director:r.director,posterUrl:r.poster_url,backdropUrl:r.backdrop_url,trailerUrl:r.trailer_url,isTrending:r.is_trending,isFeatured:r.is_featured,genres:r.genres??[],cast:r.cast_members??[],viewCount:Number(r.view_count??0),status:r.status,published:r.status==="published",source:r.source,managedByAdmin:r.managed_by_admin});
async function syncOphim(movies:any[]){if(!movies.length)return;const client=await pool.connect();try{await client.query("BEGIN");for(const m of movies){if(!m.id||!m.title)continue;await client.query(`INSERT INTO movies(id,slug,source,source_slug,managed_by_admin,last_synced_at,title,original_title,description,release_year,duration_minutes,age_rating,rating,match_score,content_type,director,poster_url,backdrop_url,trailer_url,genres,cast_members,country,language,is_trending,is_featured,status,published_at) VALUES($1,$1,'ophim',$1,FALSE,NOW(),$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,'published',NOW()) ON CONFLICT(id) DO UPDATE SET last_synced_at=NOW(),title=EXCLUDED.title,original_title=EXCLUDED.original_title,description=EXCLUDED.description,release_year=EXCLUDED.release_year,duration_minutes=EXCLUDED.duration_minutes,age_rating=EXCLUDED.age_rating,rating=EXCLUDED.rating,match_score=EXCLUDED.match_score,content_type=EXCLUDED.content_type,director=EXCLUDED.director,poster_url=EXCLUDED.poster_url,backdrop_url=EXCLUDED.backdrop_url,trailer_url=EXCLUDED.trailer_url,genres=EXCLUDED.genres,cast_members=EXCLUDED.cast_members,country=EXCLUDED.country,language=EXCLUDED.language,is_trending=EXCLUDED.is_trending,is_featured=EXCLUDED.is_featured WHERE movies.managed_by_admin=FALSE`,[m.id,m.title,m.originalTitle??"",m.description||"Thông tin đang cập nhật.",Math.min(2200,Math.max(1888,Number(m.year)||new Date().getFullYear())),Math.max(1,Number(m.durationMinutes)||1),m.ageRating||"HD",Number(m.rating)||0,Number(m.matchScore)||80,m.type==="movie"?"movie":"series",m.director||"Đang cập nhật",m.posterUrl||"https://placehold.co/420x630",m.backdropUrl||m.posterUrl||"https://placehold.co/1280x720",m.trailerUrl||"",m.genres??[],m.cast??[],Array.isArray(m.country)?m.country.join(", "):(m.country??null),m.language??null,!!m.isTrending,!!m.isFeatured]);for(let i=0;i<(m.genreSlugs??[]).length;i++){const slug=m.genreSlugs[i],name=m.genres?.[i]??slug;await client.query(`INSERT INTO genres(id,name,slug,position,active) VALUES($1,$2,$1,999,TRUE) ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name`,[slug,name])}}await client.query("COMMIT")}catch(error){await client.query("ROLLBACK");throw error}finally{client.release()}}
async function overlayOphim(movies:any[]){if(!movies.length)return [];const rows=(await pool.query("SELECT * FROM movies WHERE id=ANY($1)",[movies.map(m=>m.id)])).rows,byId=new Map(rows.map(r=>[r.id,r]));return movies.flatMap(movie=>{const row=byId.get(movie.id);if(!row||row.status!=="published")return [];const local=mapMovie(row);return [{...movie,...local,slug:movie.slug,quality:movie.quality,language:row.language??movie.language,country:movie.country,episodeCurrent:movie.episodeCurrent,genreSlugs:movie.genreSlugs,episodes:movie.episodes}]})}
const movieSchema=z.object({title:z.string().trim().min(1),originalTitle:z.string().optional().default(""),description:z.string().min(10),year:z.number().int().min(1888).max(2200),durationMinutes:z.number().int().positive(),ageRating:z.string().min(1).max(10),type:z.enum(["movie","series"]),director:z.string().min(1),posterUrl:z.string().url(),backdropUrl:z.string().url(),trailerUrl:z.string().url(),genres:z.array(z.string()).min(1),cast:z.array(z.string()).default([]),isTrending:z.boolean().default(false),isFeatured:z.boolean().default(false),status:z.enum(["draft","published","archived"]).default("published")});

app.use("/v1/admin/content",adminContentRouter);
app.use("/v1/admin/genres",adminGenresRouter);

app.get("/v1/catalog/genres",asyncHandler(async(_q,res)=>ok(res,(await pool.query("SELECT id,name,slug FROM genres ORDER BY name")).rows)));
app.get("/v1/catalog/movies",asyncHandler(async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),size=Math.min(50,Math.max(1,Number(req.query.pageSize)||24)),genre=String(req.query.genre??""),sort=String(req.query.sort??"trending"),kids=req.query.kids==="true";const where=["m.status='published'"];const params:any[]=[];if(genre){params.push(genre);where.push(`$${params.length}=ANY(m.genres)`)}if(kids)where.push("m.age_rating IN ('P','K','G','PG','7+','10+','12+')");const order=sort==="rating"?"m.rating DESC":sort==="newest"?"m.release_year DESC":"m.is_trending DESC,m.view_count DESC,m.rating DESC";const count=await pool.query(`SELECT COUNT(*)::int count FROM movies m WHERE ${where.join(" AND ")}`,params);params.push(size,(page-1)*size);const rows=await pool.query(`SELECT m.* FROM movies m WHERE ${where.join(" AND ")} ORDER BY ${order} LIMIT $${params.length-1} OFFSET $${params.length}`,params);ok(res,rows.rows.map(mapMovie),{page,pageSize:size,total:count.rows[0].count,totalPages:Math.ceil(count.rows[0].count/size)})}));
app.get("/v1/catalog/movies/:id",asyncHandler(async(req,res)=>{const row=(await pool.query("SELECT * FROM movies WHERE id=$1 AND status='published'",[req.params.id])).rows[0];if(!row)return fail(res,404,"MOVIE_NOT_FOUND","Movie not found");ok(res,mapMovie(row))}));
app.get("/v1/search",asyncHandler(async(req,res)=>{const q=String(req.query.q??"").trim();if(!q)return ok(res,[]);const rows=await pool.query(`SELECT * FROM movies WHERE status='published' AND (search_document @@ websearch_to_tsquery('simple',$1) OR title ILIKE $2 OR director ILIKE $2 OR EXISTS(SELECT 1 FROM unnest(cast_members) c WHERE c ILIKE $2)) ORDER BY ts_rank(search_document,websearch_to_tsquery('simple',$1)) DESC,rating DESC LIMIT 20`,[q,`%${q}%`]);ok(res,rows.rows.map(mapMovie))}));
app.get("/v1/recommendations/similar/:id",asyncHandler(async(req,res)=>{const rows=await pool.query(`SELECT candidate.* FROM movies source JOIN movies candidate ON candidate.id<>source.id AND candidate.genres&&source.genres WHERE source.id=$1 AND candidate.status='published' ORDER BY cardinality(ARRAY(SELECT unnest(candidate.genres) INTERSECT SELECT unnest(source.genres))) DESC,candidate.rating DESC LIMIT 8`,[req.params.id]);ok(res,rows.rows.map(mapMovie))}));
app.post("/internal/content-view",asyncHandler(async(req,res)=>{if(req.header("x-internal-secret")!==(process.env.INTERNAL_SECRET??"local-internal-secret"))return fail(res,401,"UNAUTHORIZED","Invalid internal secret");const id=String(req.body.contentId??"");if(id)await pool.query("UPDATE movies SET view_count=view_count+1 WHERE id=$1",[id]);ok(res,{recorded:!!id})}));
app.post("/v1/catalog/movies",requireAdmin,asyncHandler(async(req,res)=>{const parsed=movieSchema.safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","Invalid movie payload",parsed.error.flatten());const v=parsed.data,id=`mov_${nanoid(16)}`;const row=(await pool.query(`INSERT INTO movies(id,title,original_title,description,release_year,duration_minutes,age_rating,content_type,director,poster_url,backdrop_url,trailer_url,genres,cast_members,is_trending,is_featured,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[id,v.title,v.originalTitle,v.description,v.year,v.durationMinutes,v.ageRating,v.type,v.director,v.posterUrl,v.backdropUrl,v.trailerUrl,v.genres,v.cast,v.isTrending,v.isFeatured,v.status])).rows[0];ok(res,mapMovie(row),null,201)}));
app.put("/v1/catalog/movies/:id",requireAdmin,asyncHandler(async(req,res)=>{const parsed=movieSchema.safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","Invalid movie payload",parsed.error.flatten());const v=parsed.data;const row=(await pool.query(`UPDATE movies SET title=$1,original_title=$2,description=$3,release_year=$4,duration_minutes=$5,age_rating=$6,content_type=$7,director=$8,poster_url=$9,backdrop_url=$10,trailer_url=$11,genres=$12,cast_members=$13,is_trending=$14,is_featured=$15,status=$16,managed_by_admin=TRUE,updated_at=NOW() WHERE id=$17 RETURNING *`,[v.title,v.originalTitle,v.description,v.year,v.durationMinutes,v.ageRating,v.type,v.director,v.posterUrl,v.backdropUrl,v.trailerUrl,v.genres,v.cast,v.isTrending,v.isFeatured,v.status,req.params.id])).rows[0];if(!row)return fail(res,404,"MOVIE_NOT_FOUND","Movie not found");ok(res,mapMovie(row))}));
app.delete("/v1/catalog/movies/:id",requireAdmin,asyncHandler(async(req,res)=>{const result=await pool.query("UPDATE movies SET status='archived',managed_by_admin=TRUE,updated_at=NOW() WHERE id=$1",[req.params.id]);if(!result.rowCount)return fail(res,404,"MOVIE_NOT_FOUND","Movie not found");ok(res,{archived:req.params.id})}));
app.use(errorMiddleware);async function start(){try{await pool.query("ALTER TABLE movies ALTER COLUMN id TYPE varchar(160)");await pool.query("CREATE TABLE IF NOT EXISTS external_api_cache(cache_key varchar(240) PRIMARY KEY,payload jsonb NOT NULL,fetched_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL)");await pool.query("CREATE INDEX IF NOT EXISTS idx_external_cache_expiry ON external_api_cache(expires_at)")}catch(error){console.error("catalog migration skipped",error)}app.listen(Number(process.env.PORT??4102),()=>console.log("catalog-service listening"))}void start();
