-- pgAdmin: mở Query Tool trên database catalog_db rồi chạy toàn bộ file này.
CREATE TABLE IF NOT EXISTS genres(id varchar(40) PRIMARY KEY,name varchar(80) UNIQUE NOT NULL,slug varchar(80) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS movies(id varchar(160) PRIMARY KEY,title varchar(255) NOT NULL,original_title varchar(255) NOT NULL DEFAULT '',description text NOT NULL,release_year int NOT NULL CHECK(release_year BETWEEN 1888 AND 2200),duration_minutes int NOT NULL CHECK(duration_minutes>0),age_rating varchar(10) NOT NULL,rating numeric(3,1) NOT NULL DEFAULT 0 CHECK(rating BETWEEN 0 AND 10),match_score int NOT NULL DEFAULT 80 CHECK(match_score BETWEEN 0 AND 100),content_type varchar(10) NOT NULL CHECK(content_type IN('movie','series')),director varchar(150) NOT NULL,poster_url text NOT NULL,backdrop_url text NOT NULL,trailer_url text NOT NULL,genres text[] NOT NULL DEFAULT '{}',cast_members text[] NOT NULL DEFAULT '{}',is_trending boolean NOT NULL DEFAULT false,is_featured boolean NOT NULL DEFAULT false,status varchar(15) NOT NULL DEFAULT 'draft' CHECK(status IN('draft','published','archived')),view_count bigint NOT NULL DEFAULT 0,search_document tsvector,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE movies ALTER COLUMN id TYPE varchar(160);
CREATE TABLE IF NOT EXISTS external_api_cache(cache_key varchar(240) PRIMARY KEY,payload jsonb NOT NULL,fetched_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS idx_external_cache_expiry ON external_api_cache(expires_at);
CREATE OR REPLACE FUNCTION movies_search_update() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.search_document:=to_tsvector('simple',coalesce(NEW.title,'')||' '||coalesce(NEW.original_title,'')||' '||coalesce(NEW.description,'')||' '||coalesce(NEW.director,'')||' '||array_to_string(NEW.genres,' ')||' '||array_to_string(NEW.cast_members,' '));RETURN NEW;END $$;
DROP TRIGGER IF EXISTS trg_movies_search ON movies;CREATE TRIGGER trg_movies_search BEFORE INSERT OR UPDATE OF title,original_title,description,director,genres,cast_members ON movies FOR EACH ROW EXECUTE FUNCTION movies_search_update();
CREATE INDEX IF NOT EXISTS idx_movies_search ON movies USING gin(search_document);CREATE INDEX IF NOT EXISTS idx_movies_genres ON movies USING gin(genres);CREATE INDEX IF NOT EXISTS idx_movies_discovery ON movies(status,is_trending,view_count DESC);
INSERT INTO genres VALUES('g-action','Hành động','hanh-dong'),('g-drama','Tâm lý','tam-ly'),('g-scifi','Viễn tưởng','vien-tuong'),('g-korean','Hàn Quốc','han-quoc'),('g-family','Gia đình','gia-dinh'),('g-thriller','Gay cấn','gay-can') ON CONFLICT DO NOTHING;
INSERT INTO movies(id,title,original_title,description,release_year,duration_minutes,age_rating,rating,match_score,content_type,director,poster_url,backdrop_url,trailer_url,genres,cast_members,is_trending,is_featured,status,view_count) VALUES
('m-neon-delta','Neon Delta','Neon Delta','Cuộc truy vết trong thành phố tương lai, nơi mọi màn hình đều có thể là một cái bẫy.',2026,128,'16+',8.8,98,'movie','Bảo Võ','https://images.unsplash.com/photo-1601814933824-fd0b574dd592?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=1800&q=80','https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',ARRAY['Viễn tưởng','Hành động','Gay cấn'],ARRAY['An Lê','Mira Trần','Kai Nguyễn'],true,true,'published',18420),
('m-silent-bay','Vịnh Lặng Im','Silent Bay','Một thị trấn biển yên ả che giấu vụ án mất tích kéo dài hơn mười năm.',2025,112,'13+',8.2,93,'series','Mai Nguyễn','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1800&q=80','https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',ARRAY['Tâm lý','Gay cấn'],ARRAY['Lan Huỳnh','Khoa Phạm'],true,true,'published',15310),
('m-house-of-lanterns','Nhà Đèn Lồng','House of Lanterns','Ba thế hệ trong gia đình làm đèn lồng tìm cách giữ lại nghề và bí mật của mình.',2024,101,'P',7.9,89,'movie','Linh Đỗ','https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1514539079130-25950c84af65?auto=format&fit=crop&w=1800&q=80','https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',ARRAY['Gia đình','Tâm lý'],ARRAY['Thu Hà','Nam Sơn'],false,false,'published',6830),
('m-seoul-after-midnight','Seoul Sau Nửa Đêm','Seoul After Midnight','Một đầu bếp trẻ bị cuốn vào đường dây nguyên liệu hiếm trong khu chợ đêm Seoul.',2026,117,'16+',8.5,96,'movie','Park Joon','https://images.unsplash.com/photo-1517722014278-c256a91a6fba?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1538485399081-7c8ed1f80f04?auto=format&fit=crop&w=1800&q=80','https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',ARRAY['Hàn Quốc','Hành động'],ARRAY['Ji Han','Min Seo'],true,false,'published',14700),
('m-orbit-9','Quỹ Đạo Số 9','Orbit 9','Đoàn phi hành gia cuối cùng phải chọn giữa về nhà và cứu trạm nghiên cứu bị bỏ quên.',2023,134,'13+',8.1,91,'movie','Huy Phan','https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1800&q=80','https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',ARRAY['Viễn tưởng','Tâm lý'],ARRAY['Minh Hồ','Rae Kim'],false,true,'published',9340),
('m-last-train','Chuyến Tàu Cuối','The Last Train','Những người xa lạ bị kẹt trên chuyến tàu xuyên đêm khi thành phố mất điện toàn bộ.',2025,98,'18+',7.7,84,'movie','Sơn Trần','https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=600&q=80','https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1800&q=80','https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',ARRAY['Gay cấn','Hành động'],ARRAY['Bảo Anh','Quốc Thịnh'],true,false,'published',11090) ON CONFLICT DO NOTHING;
