import "dotenv/config";
import express from "express";
import { nanoid } from "nanoid";
import { z } from "zod";
import { asyncHandler, createPool, errorMiddleware, fail, health, identity, ok, requireIdentity, requireRoles } from "@movie-platform/service-kit";

const app=express(),pool=createPool("review_db");app.use(express.json());app.get("/health",health("review-service",pool));
const dto=(r:any)=>({id:r.id,movieId:r.content_id,movieTitle:r.content_title,moviePosterUrl:r.content_poster_url,profileId:r.profile_id,profileName:r.profile_name,rating:r.rating,content:r.comment,spoiler:r.is_spoiler,likeCount:r.like_count,reportCount:Number(r.report_count??0),likedByMe:r.liked_by_me??false,createdAt:r.created_at,updatedAt:r.updated_at});

app.get("/v1/reviews/content/:contentId",asyncHandler(async(req,res)=>{const profile=identity(req)?.profileId??"";const rows=await pool.query(`SELECT r.*,EXISTS(SELECT 1 FROM review_reactions x WHERE x.review_id=r.id AND x.profile_id=$2 AND x.reaction='like') liked_by_me FROM reviews r WHERE content_id=$1 AND status='approved' ORDER BY like_count DESC,created_at DESC`,[req.params.contentId,profile]);const summary=await pool.query("SELECT COUNT(*)::int total,COALESCE(ROUND(AVG(rating)::numeric,1),0) average FROM reviews WHERE content_id=$1 AND status='approved'",[req.params.contentId]);ok(res,{reviews:rows.rows.map(dto),summary:{total:summary.rows[0].total,average:Number(summary.rows[0].average)}})}));
app.post("/v1/reviews/content/:contentId",requireIdentity,asyncHandler(async(req,res)=>{const parsed=z.object({rating:z.number().int().min(1).max(5),content:z.string().trim().min(3).max(2000),spoiler:z.boolean().default(false),profileName:z.string().trim().min(1).max(80).default("Người xem"),contentTitle:z.string().trim().max(255).optional(),contentPosterUrl:z.string().url().optional()}).safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","Nội dung đánh giá không hợp lệ",parsed.error.flatten());const v=parsed.data,row=(await pool.query(`INSERT INTO reviews(id,content_id,content_title,content_poster_url,profile_id,profile_name,rating,comment,is_spoiler,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'approved') ON CONFLICT(content_id,profile_id) DO UPDATE SET content_title=COALESCE(EXCLUDED.content_title,reviews.content_title),content_poster_url=COALESCE(EXCLUDED.content_poster_url,reviews.content_poster_url),rating=EXCLUDED.rating,comment=EXCLUDED.comment,is_spoiler=EXCLUDED.is_spoiler,status='approved',moderated_by=NULL,moderated_at=NULL,updated_at=NOW() RETURNING *`,[`rev_${nanoid(16)}`,req.params.contentId,v.contentTitle??null,v.contentPosterUrl??null,identity(req)!.profileId,v.profileName,v.rating,v.content,v.spoiler])).rows[0];ok(res,{...dto(row),status:row.status,message:"Đánh giá đã được đăng"},null,201)}));
app.post("/v1/reviews/:reviewId/like",requireIdentity,asyncHandler(async(req,res)=>{const client=await pool.connect();try{await client.query("BEGIN");const existing=await client.query("DELETE FROM review_reactions WHERE review_id=$1 AND profile_id=$2 RETURNING 1",[req.params.reviewId,identity(req)!.profileId]);if(!existing.rowCount)await client.query("INSERT INTO review_reactions(review_id,profile_id,reaction) VALUES($1,$2,'like')",[req.params.reviewId,identity(req)!.profileId]);await client.query("UPDATE reviews SET like_count=(SELECT COUNT(*) FROM review_reactions WHERE review_id=$1 AND reaction='like') WHERE id=$1",[req.params.reviewId]);await client.query("COMMIT");ok(res,{liked:!existing.rowCount})}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}}));
app.delete("/v1/reviews/:reviewId",requireIdentity,asyncHandler(async(req,res)=>{const actor=identity(req)!;const isAdmin=["admin","super_admin","content_editor","support"].includes(actor.role);const result=await pool.query("DELETE FROM reviews WHERE id=$1 AND (profile_id=$2 OR $3::boolean)",[req.params.reviewId,actor.profileId,isAdmin]);if(!result.rowCount)return fail(res,404,"REVIEW_NOT_FOUND","Không tìm thấy đánh giá");ok(res,{deleted:req.params.reviewId})}));

app.get("/v1/admin/reviews",requireRoles("super_admin","content_editor","support"),asyncHandler(async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||20)),status=String(req.query.status??""),contentId=String(req.query.contentId??""),q=String(req.query.q??"").trim(),rating=Number(req.query.rating)||0,reported=req.query.reported==="true",sort=String(req.query.sort??"newest");const params:any[]=[],where:string[]=[];if(status){params.push(status);where.push(`r.status=$${params.length}`)}if(contentId){params.push(contentId);where.push(`r.content_id=$${params.length}`)}if(rating){params.push(rating);where.push(`r.rating=$${params.length}`)}if(q){params.push(q);where.push(`r.search_document @@ websearch_to_tsquery('simple',$${params.length})`)}if(reported)where.push(`EXISTS(SELECT 1 FROM review_reports rr WHERE rr.review_id=r.id)`);const clause=where.length?`WHERE ${where.join(" AND ")}`:"",order=sort==="reported"?"report_count DESC,r.created_at DESC":sort==="rating_low"?"r.rating ASC,r.created_at DESC":"r.created_at DESC";const total=Number((await pool.query(`SELECT COUNT(*) count FROM reviews r ${clause}`,params)).rows[0].count);params.push(limit,(page-1)*limit);const rows=await pool.query(`SELECT r.*,(SELECT COUNT(*) FROM review_reports rr WHERE rr.review_id=r.id)::int report_count FROM reviews r ${clause} ORDER BY ${order} LIMIT $${params.length-1} OFFSET $${params.length}`,params);const summary=await pool.query("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='hidden' OR status='rejected')::int hidden,COALESCE(ROUND(AVG(rating) FILTER(WHERE status='approved')::numeric,1),0) average,(SELECT COUNT(DISTINCT review_id)::int FROM review_reports) reported FROM reviews");ok(res,{items:rows.rows.map(r=>({...dto(r),status:r.status,moderatedBy:r.moderated_by,moderatedAt:r.moderated_at})),summary:{...summary.rows[0],average:Number(summary.rows[0].average)},pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}})}));
app.patch("/v1/admin/reviews/bulk/status",requireRoles("super_admin","content_editor","support"),asyncHandler(async(req,res)=>{const parsed=z.object({ids:z.array(z.string()).min(1).max(100),status:z.enum(["approved","hidden","rejected"])}).safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","Thao tác hàng loạt không hợp lệ");const result=await pool.query("UPDATE reviews SET status=$1,moderated_by=$2,moderated_at=NOW(),updated_at=NOW() WHERE id=ANY($3)",[parsed.data.status,identity(req)!.userId,parsed.data.ids]);ok(res,{updated:result.rowCount})}));
app.post("/v1/reviews/:reviewId/report",requireIdentity,asyncHandler(async(req,res)=>{const parsed=z.object({reason:z.enum(["spam","abuse","spoiler","harassment","other"]),detail:z.string().trim().max(500).optional()}).safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","Lý do báo cáo không hợp lệ");await pool.query(`INSERT INTO review_reports(id,review_id,profile_id,reason,detail) VALUES($1,$2,$3,$4,$5) ON CONFLICT(review_id,profile_id) DO UPDATE SET reason=EXCLUDED.reason,detail=EXCLUDED.detail,created_at=NOW()`,[`rrp_${nanoid(16)}`,req.params.reviewId,identity(req)!.profileId,parsed.data.reason,parsed.data.detail??null]);ok(res,{reported:true},null,201)}));
app.patch("/v1/admin/reviews/:reviewId/status",requireRoles("super_admin","content_editor","support"),asyncHandler(async(req,res)=>{const parsed=z.object({status:z.enum(["approved","hidden","rejected"])}).safeParse(req.body);if(!parsed.success)return fail(res,400,"VALIDATION_ERROR","Trạng thái kiểm duyệt không hợp lệ");const row=(await pool.query("UPDATE reviews SET status=$1,moderated_by=$2,moderated_at=NOW(),updated_at=NOW() WHERE id=$3 RETURNING id,status,moderated_at",[parsed.data.status,identity(req)!.userId,req.params.reviewId])).rows[0];if(!row)return fail(res,404,"REVIEW_NOT_FOUND","Không tìm thấy đánh giá");ok(res,row)}));
app.delete("/v1/admin/reviews/:reviewId",requireRoles("super_admin"),asyncHandler(async(req,res)=>{const result=await pool.query("DELETE FROM reviews WHERE id=$1",[req.params.reviewId]);if(!result.rowCount)return fail(res,404,"REVIEW_NOT_FOUND","Không tìm thấy đánh giá");ok(res,{id:req.params.reviewId,deleted:true})}));

app.use(errorMiddleware);async function start(){try{await pool.query("ALTER TABLE reviews ALTER COLUMN content_id TYPE varchar(160)")}catch(error){console.error("review migration skipped",error)}app.listen(Number(process.env.PORT??4104),()=>console.log("review-service listening"))}void start();
